### ISSUE TITLE
Administrator rights

### ISSUE THREAD

**Issue by carstenbauer** [ffreyer/BinningAnalysis.jl#11]
Hi @ffreyer,

if you give me administrator rights here I can try to move the issues to https://github.com/crstnbr/BinningAnalysis.jl

Best
Carsten

**Comment by carstenbauer** [comment]
Actually, maybe you can try it yourself:

https://help.github.com/articles/transferring-an-issue-to-another-repository/

**Comment by ffreyer** [comment]
I guess we want to transfer all issues?

**Comment by carstenbauer** [comment]
Sure.

**Comment by ffreyer** [comment]
Your repository doesn't show up as a transfer target for me, so I guess you'll have to try

**Comment by carstenbauer** [comment]
Doesn't work for me either.... I guess it's not important. Let's move manually or fix them right away.
